export const dranken = {
    dranken: [
        {
            id: 1,
            naam: "Coca-Cola",
            currentPrijs: 2.5,
            previousPrijs: 2.25,
            categorie: "frisdrank",
            alcoholisch: false,
            kleur: "#000000",
            afbeelding: '/images/logos/coca_cola-logo.jpg',
            hotkey: "c",
        },
        {
            id: 2,
            naam: "Stella Artois",
            currentPrijs: 3.5,
            previousPrijs: 3.25,
            categorie: "bier",
            alcoholisch: true,
            kleur: "#ffff00",
            afbeelding: '/images/logos/stella_artois-logo.jpg',
            hotkey: "a",
        },
        {
            id: 3,
            naam: "Duvel",
            currentPrijs: 4.5,
            previousPrijs: 4.25,
            categorie: "bier",
            alcoholisch: true,
            kleur: "#ff0000",
            afbeelding: '/images/logos/duvel-logo.png',
            hotkey: "d",
        },
        {
            id: 4,
            naam: "Fanta",
            currentPrijs: 2.25,
            previousPrijs: 2,
            categorie: "frisdrank",
            alcoholisch: false,
            kleur: "#ff6600",
            afbeelding: '/images/logos/fanta-logo.png',
            hotkey: "f",
        },
        {
            id: 5,
            naam: "Jupiler",
            currentPrijs: 3.75,
            previousPrijs: 3.5,
            categorie: "bier",
            alcoholisch: true,
            kleur: "#ffcc00",
            afbeelding: '/images/logos/jupiler-logo.jpeg',
            hotkey: "j",
        },
        {
            id: 6,
            naam: "Leffe",
            currentPrijs: 4.75,
            previousPrijs: 4.5,
            categorie: "bier",
            alcoholisch: true,
            kleur: "#663300",
            afbeelding: '/images/logos/leffe-logo.png',
            hotkey: "l",
        },
        {
            id: 7,
            naam: "Sprite",
            currentPrijs: 2.25,
            previousPrijs: 2,
            categorie: "frisdrank",
            alcoholisch: false,
            kleur: "#00ff00",
            afbeelding: '/images/logos/sprite-logo.jpg',
            hotkey: "s",
        },
        {
            id: 8,
            naam: "Hoegaarden",
            currentPrijs: 4,
            previousPrijs: 3.75,
            categorie: "bier",
            alcoholisch: true,
            kleur: "#ffffff",
            afbeelding: '/images/logos/hoegaarden-logo.png',
            hotkey: "h",
        },
        {
            id: 9,
            naam: "Chaudfontaine",
            currentPrijs: 2.75,
            previousPrijs: 2.5,
            categorie: "water",
            alcoholisch: false,
            kleur: "#0000ff",
            afbeelding: '/images/logos/chaudfontaine-logo.png',
            hotkey: "c",
        },
        {
            id: 10,
            naam: "Orval",
            currentPrijs: 5,
            previousPrijs: 4.75,
            categorie: "bier",
            alcoholisch: true,
            kleur: "#ff9900",
            afbeelding: '/images/logos/orval-logo.jpeg',
            hotkey: "o",
        },
    ],
};
